accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    #path('profile/<username>', views.profile, name='profile'),
    #path('', views.profile, name='profile'),
    #path('edit', views.user_update, name='update'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
]

chat/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'chat'
urlpatterns = [
    path('', RedirectView.as_view(url='chat/')),
    path('chat/', views.IndexView.as_view(), name='index'),
]

rip_my_iphone/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView

def robots(request):
    return HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')

urlpatterns = [
    path('robots.txt', robots),
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=75, unique=True, default="")

    username = models.CharField(
        'username',
        max_length=150,
        unique=True,
        help_text='autogenerated uuid',
        validators=[AbstractUser.username_validator],
        error_messages={
            'unique': "A user with that username already exists.",
        },
        blank = True
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


#I don't fill out the username field, I only fill out the name field -- so this autofills the username filed with some uuid
def random_username(sender, instance, **kwargs):
    if not instance.username:
        instance.username = uuid.uuid4().hex[:30]
models.signals.pre_save.connect(random_username, sender=User)

chat/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User

# a message has some text, and someone who sends it
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                             related_name="messages")
    content = models.TextField(blank=True, null=True)
    time = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['time']

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from .models import User

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields.pop('username')

    name = forms.ModelChoiceField(queryset=User.objects.all())
    password = forms.CharField(widget=forms.PasswordInput())
    field_order=['name','password']

    def clean(self):
        name = self.cleaned_data.get('name')
        password = self.cleaned_data.get('password')

        if name is not None and password:
            username = User.objects.get(name=name).username
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

chat/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["content"]
        labels = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 3})}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) # Get the user from kwargs
        super(MessageForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(MessageForm, self).save(commit=False)
        if self.user:
            instance.user = self.user
        if commit:
            instance.save()
        return instance

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.views import LoginView
from django.contrib.auth import logout

from .models import User
from .forms import *

class Login(LoginView):
    authentication_form=UserLoginForm
    redirect_authenticated_user = True

def logout_view(request):
    logout(request)
    #messages.success(request, 'logged out')
    return HttpResponseRedirect(reverse('accounts:login'))

chat/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import *
from .forms import *

# Create your views here.
class IndexView(generic.edit.CreateView):
    template_name = 'chat/index.html'
    form_class = MessageForm
    success_url = reverse_lazy('chat:index')

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['objects'] = Message.objects.all()
       return context

    def form_valid(self, form):
        form.instance.user = self.request.user # Add the user to the form instance
        return super().form_valid(form)

chat/templates/chat/index.html
{% extends "base.html" %}

{% block content %}
<h1>Talk to Cassidy</h1>
<p><i>just remember that these aren't DM's, you're talking with me and everyone else who is in the user drop down you saw when you logged in</i></p>

{% for message in objects %}
<div class='message{% if message.user == user %} me{% endif %}'>
  <p><b>{{ message.user }}</b> {{ message.time }}</p>
  <pre>{{ message }} </pre>
</div>
{% endfor %}

<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="send message">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="Messages">
    <meta name="author" content="Cassidy Diamond">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/png" />

    <title>{% block title %}rip cassie's iphone 🙏{% endblock %}</title>
    <link type="text/css" href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="is-{{ message.tags }}"{% endif %}>
	  {{ message }}<span class='close' onclick="close_message(this)" aria-label="close message">✖</span>
      </li>
    {% endfor %}
  </ul>
  {% endif %}

  {% include "navbar.html" %}
  {% block content %}
  {% endblock %}

<script>
  function close_message(el){
    el.parentElement.remove();
  }
</script>
<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

templates/navbar.html
<nav>
  {% if request.user.is_authenticated %}
  <a href="{% url 'accounts:logout' %}" class='float-right'>log out, {{ user.name }}</a>
  {% else %} <a href="{% url 'accounts:login' %}" class='float-right'>log in</a>
  {% endif %}
</nav>